trigger:
  - main
  - develop

variables:
  pythonVersion: '3.12'
  dockerImageName: 'newser-bot'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
  - stage: Test
    displayName: 'Run Tests'
    jobs:
      - job: RunPytest
        displayName: 'Run Pytest'
        pool:
          name: 'Default'  # używamy self-hosted agenta
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true
            displayName: 'Set up Python $(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - script: |
              pytest
            displayName: 'Run pytest'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/test-results.xml'
            condition: succeededOrFailed()
            displayName: 'Publish test results'

  - stage: Build
    displayName: 'Build Docker Image'
    dependsOn: Test
    condition: succeeded()
    jobs:
      - job: DockerBuild
        displayName: 'Build Docker Image'
        pool:
          name: 'Default'  # używamy self-hosted agenta
        steps:
          - task: Docker@2
            inputs:
              command: 'build'
              dockerfile: '$(dockerfilePath)'
              tags: |
                $(tag)
            displayName: 'Build Docker Image'
